---
id: koward
name: Koward
full: Kolab server administration application
description: |
  This package provides a web based frontend for the
  administration of the Kolab server.
list: horde
type: application
